Add Theia.cloud monitor
eclipsesource/theia-cloud pull request #107
Opened 2022-11-18 13:38 UTC by sgraband

- Added monitor module to operator: -- Can be enabled with `--enableMonitor`
-- Requires extension to be installed in the app
-- Specific modules can be turned on or off

- Added vscode extension to startup Monitor endpoints: -- Will be called by the operator
-- Has modules that can be turned on or off

- Added Monitor modules: -- Messaging module:
--- Allows the operator to send messages to the application --- They will be displayed to the user
--- Generic timeout message, when the pod shuts down -- ActivityTracker module:
--- The extension tracks the last activity of the user --- Operator can ask for last activity via endpoint --- A message can be displayed if the pod will shutdown soon

- Adjusted the helm chart and CRDs to be able to configure the monitor

To test:
- Delete CRDs
	- kubectl delete crd sessions.theia.cloud
	- kubectl delete crd appdefinitions.theia.cloud
- Build local images:
	- docker build -t theia-cloud-operator:local -f dockerfiles/operator/Dockerfile . 
	- docker build -t theia-cloud-demo:local -f demo/dockerfiles/demo-theia-monitor-vscode/Dockerfile demo/dockerfiles/demo-theia-monitor-vscode/.
- Use local images:
	- adjust the valuesMinikubeMonitor.yaml:
	- replace operator.image with theia-cloud-operator:local
	- replace image.name with theia-cloud-demo:local
- Reduce waiting time:
	- theia-appdefinition-spec.yaml: adjust the timeoutAfter and notifyAfter values so you dont have to wait for 30 minutes.

2022-11-18 15:52 UTC, lucas-koehler requested changes
Looks quite good already. I added some questions and suggestions.
Also, is this file `node/monitor/workspace/test.txt` really needed?
I did not test it yet. I think it more worthwhile once the secret, etc is in, too.

2022-11-18 15:52 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/monitor/MonitorActivityTrackerImpl.java
> +		RequestBody body = RequestBody.create(mediaType, "");
Why do we need an empty request body? Is it mandatory?

2022-11-18 15:52 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/monitor/MonitorMessagingServiceImpl.java
> +	if (arguments.isEnableMonitor()) {
Maybe refactor out this check to a protected method `isEnabled` or something like that. This avoids duplicating this 3 times and would also enable subclasses to extend this behavior dynamically.

2022-11-18 15:52 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/monitor/MonitorMessagingServiceImpl.java
> +		e.printStackTrace();
Should this be handled via a proper log message?

2022-11-18 15:52 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/resources/templateService.yaml
> +    - name: express
minor: maybe this should be named monitor or monitor-express after its functionality. When looking at this in the resource that tells an admin more than `express` which just suggests any web service running on express.

2022-11-18 15:52 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/resources/templateServiceWithoutOAuthProxy.yaml
> +    - name: express
minor: maybe this should be named monitor or monitor-express after its functionality. When looking at this in the resource that tells an admin more than express which just suggests any web service running on express.

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/README.md
> +VSCode extension to monitor Theia.cloud hosted VSCode/Theia products. The extension will expose a rest service, where an external service can ping the extension to get information about the pod.
```suggestion
VSCode extension to monitor Theia.cloud hosted VSCode/Theia products.
The extension exposes a rest service that an external service can ping to get information about the pod.
```

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/README.md
> +The extension is designed to allow other modules to be added in the future.
```suggestion
The extension is designed to facilitate the addition of further modules in the future.
```

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/README.md
> +For this the extension will read out environment variables to check if a specific module should be activated.
```suggestion
For this, the extension reads environment variables to check the activation of each corresponding module.
```

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/README.md
> +For an example of how these environment variables should be set, take a look at `Run extension` launch config the `.vscode/launch.json` file.
```suggestion
For an example on setting these environment variables, take a look at the `Run extension` launch config in the `.vscode/launch.json` file.
```

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/package.json
> +  "name": "theiacloud-monitor",
Add `contributors`, `license`, `bugs` fields

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/src/extension.ts
> + * Starts the REST service and registers the endpoints of all enabled TrackerModules's
```suggestion
 * Starts the REST service and registers the endpoints of all enabled TrackerModules
```

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/src/extension.ts
> + * Utility method to check which TrackerModules's are enabled
```suggestion
 * Utility method to check which TrackerModules are enabled
```

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/src/extension.ts
> + * @returns the list of enabled TrackerModule's
```suggestion
 * @returns the list of enabled TrackerModules
```

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/src/extension.ts
> +	if (getFromEnv(MONITOR_ENABLE_ACTIVITY_TRACKER) === '1') {
Why do we use `1` and `0` for the enablement instead of true or false ? Is this a convention or am I missing something else? In other configuration places like the helm values we use true and false

2022-11-18 15:52 UTC, lucas-koehler commented on node/monitor/src/modules/activity-tracker-module.ts
> +export const COMMAND_ACTIVITY_REPORT_TITLE = 'activity.report';
Are commands scoped to the registering extension? If not we maybe should prefix with `theia.cloud` or something to avoid collisions with client extensions

2023-01-26 10:45 UTC, sgraband commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/monitor/MonitorActivityTrackerImpl.java
> +		RequestBody body = RequestBody.create(mediaType, "");
I did not get it to work without an empty body for the post requests. Maybe i missed something, but i dont think it works without a body.

2023-01-26 10:46 UTC, sgraband commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/monitor/MonitorActivityTrackerImpl.java
> +	    if (getActivityResponse.code() == 200) {
We control the response codes on the extension sides, so i would not allow more codes then the one we send on the extension. Could still be added later on if needed.

2023-01-26 10:47 UTC, sgraband commented
@lucas-koehler I updated the Pr to contain the sessionSecret in each call to the extension. The theia extension will be done in a follow up ticket/PR. Could you take another look?

2023-01-26 16:03 UTC, lucas-koehler reviewed
I tested it and it worked well for me. I have some minor inline remarks and one possible source for NPEs for adopters not using the monitoring

2023-01-30 09:35 UTC, sgraband commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/SessionSpec.java
> +		+ ", sessionSecret=" + sessionSecret + "]";
Just an oversight. Now that you mentioned it, it is probably not a good idea to put the sessionSecret inside of the toString method. I will adjust this.

2023-01-30 13:36 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/DefaultDeploymentTemplateReplacements.java
> +	    if (appDefinition.getSpec().getMonitor() != null && appDefinition.getSpec().getMonitor().getPort() != 0) {
Just a minor improvement to the check because negative ports do not make sense ;)
```suggestion
	    if (appDefinition.getSpec().getMonitor() != null && appDefinition.getSpec().getMonitor().getPort() > 0) {
```

2023-02-07 13:32 UTC, jfaltermeier commented
Sorry about the merge conflicts. These appear because the helm chart was moved to https://github.com/eclipsesource/theia-cloud-helm so it should be not that hard to fix. 
Once the conflicts are resolved, this will be the next PR to be merged.

2023-02-28 09:41 UTC, sgraband commented
I rebased the PR and opened https://github.com/eclipsesource/theia-cloud-helm/pull/13 for the helm chart changes.

2023-02-28 15:34 UTC, lucas-koehler approved these changes
Thanks for the rebase, still LGTM. I have one small question about a dependency inline

2023-02-28 15:34 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/pom.xml
> +		</dependency>
What is this needed for?

2023-03-01 07:24 UTC, sgraband commented on java/operator/org.eclipse.theia.cloud.operator/pom.xml
> +		</dependency>
IIRC this was the easiest way to create JSON objects to send to the extension.

2023-03-07 12:06 UTC, merged