Add authentication to the try now page
eclipsesource/theia-cloud pull request #145
Opened 2023-02-27 09:04 UTC by sgraband

Moved components into separate files.
Added header that contains login/logout buttons.
User email will be displayed if logged in.
Added hint for why the login is needed.

Contributed on behalf of STMicroelectronics

Additionally Github integration was added to the keycloak.

To test:
- Enable the keycloak
- Point `keycloak.authUrl` to the keycloak (https://keycloak.34.141.62.32.nip.io/) (`/auth` is no longer needed)
- Build and use the try-now-page image

2023-02-27 11:10 UTC, lucas-koehler requested changes
Hi @sgraband , the changes generally look good to me and logging in via Github worked. However, after the first login, keycloak requested additional information (see screenshot). As we neither need nor want to store this information, can we get rid of that?
![image](https://user-images.githubusercontent.com/6959840/221548616-2fe46311-24dc-4133-8201-4fd172259885.png)

2023-02-28 08:15 UTC, sgraband commented on node/try-now-page/src/components/Footer.tsx
> +        Theia.Cloud
I fixed this, but created #146 to fix the other occurences of Theia.Cloud.

2023-02-28 08:17 UTC, sgraband commented
Thank you for the review @lucas-koehler! Unfortunately i cannot reproduce the issue, that i get asked about more details. I cleaned everything (my user in the keycloak and my github oauth session) but when i login again everything is set automatically.
Could it be that there is a problem with the email address that you used, so that the first and last name are not detected?

2023-02-28 08:25 UTC, lucas-koehler approved these changes
@sgraband Thanks for the updates! I checked the account I used (a dummy account) and it indeed did not have a name set. So it makes sense to request that when it expects the profile.
Of course it would be better if a name were not required but I think it is not possible to require even less than the current scope. So this is fine for me :)

2023-03-07 13:05 UTC, merged