Add issue templates
eclipsesource/theia-cloud pull request #155
Opened 2023-03-30 11:00 UTC by lucas-koehler

- Add issue form templates for bug and feature issues
- Fix typos in SECURITY.md
- Add links to Github discussions and professional support to new issue page

Note: This PR should be squashed when merged!

2023-04-04 09:56 UTC, jfaltermeier requested changes
Thanks, looks very good already. I have two minor suggestions. 
Feel free to adjust the wording from the suggestions.

2023-04-04 09:56 UTC, jfaltermeier commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    description: The cluster provider (e.g. Minikube, AWS, GKE, Azure, Docker Desktop). Please include your OS when using a local cluster.
```suggestion
    description: The cluster provider (e.g. Minikube, AWS, GKE, Azure, Docker Desktop). Please include your OS when using a local cluster. If you are using Terraform, please inlcude the configuration files if possible.  
```

2023-04-04 09:56 UTC, jfaltermeier commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +    description: The cluster provider (e.g. Minikube, AWS, GKE, Azure, Docker Desktop) the feature is
```suggestion
    description: The cluster provider (e.g. Minikube, AWS, GKE, Azure, Docker Desktop) the feature is for. Leave out if the feature is not related to (a) specific provider(s).
```

2023-04-05 08:23 UTC, lucas-koehler commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    description: The cluster provider (e.g. Minikube, AWS, GKE, Azure, Docker Desktop). Please include your OS when using a local cluster.
FYI: I edited you suggestion because it contained a type ;)

2023-04-05 08:41 UTC, jfaltermeier approved these changes

2023-04-05 08:43 UTC, merged