Eager start can not retrieve existing services
eclipsesource/theia-cloud pull request #196
Opened 2023-07-11 19:04 UTC by paulreuter

Fixes #195

2023-07-12 14:04 UTC, lucas-koehler requested changes
Hi @paulreuter ,
thanks for the contribution :heart: . I added a small comment inline.

2023-07-12 14:04 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/util/TheiaCloudK8sUtil.java
> +	instance = instance.length() == 0 ? "" : instance.charAt(0) == 'a' ? instance.substring(1) : instance;
Could you add a comment why this is necessary, please? Otherwise, this might be very confusing when looking at this again in the future.
Even better would be adding a constant with the prefix `a` to `NamingUtil` and getting it from there :)

2023-08-07 10:12 UTC, paulreuter commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/util/TheiaCloudK8sUtil.java
> +	instance = instance.length() == 0 ? "" : instance.charAt(0) == 'a' ? instance.substring(1) : instance;
Alright, that should do it.

2023-08-07 14:18 UTC, lucas-koehler approved these changes
LGTM now, thanks again :)

2023-08-07 14:21 UTC, merged