Provide conversion webhook for CRDs
eclipsesource/theia-cloud pull request #283
Opened 2024-02-23 09:48 UTC by sgraband

Webhook is called, whenever a CR is requested in a specific version. This allows for a better updating path, as old CRs are still useable.

[conversion] Provide conversion java project:
- A webhook that offers endpoints for the three CRD types
- Is buildable as a runnable jar
- Contains Mappers from all supported versions to a hub

[common] Add Hub and previous version for all CRDs
- The hub is a superset of all values of a CRD across all versions
- Keep a copy of the old supported versions to transform back
- This is useful, as this way the the old operator still works
- Supported from these versions: - `AppDefintion.v1beta8` - `Session.v1beta6` - `Workspace.v1beta3`
- To showcase the functionality update CRDs to new version: - Move status like fields to status: - `Session.v1beta7`: Move `url`, `lastActivity` and `error` fields from the spec to the status. - `Workspace.v1beta4`: Move the `error` field from the spec to the status. Also add the `error` field to `Workspace.v1beta3` as it was missing

    - Remove `timeout.strategy` from AppDefinition
        - `AppDefinition.v1beta9`: Removed `timeout.strategy` and `timeout.limit`
        is now just `timeout`. This was done, as there is only one Strategy left.

[operator] Adjust operator so it works with the above changes.

[service] Adjust service so it works with the above changes.

[documentation] Add build command for `conversion-webhook`

[.github] Add ci for `conversion-webhook`
- Also fix publishing of new `next-version` (reusable typo)
- (I pushed the missing images manually)

Contributed on behalf of STMicroelectronics
Co-authored-by: Johannes Faltermeier <jfaltermeier@eclipsesource.com>

Helm-repo PR: https://github.com/eclipsesource/theia-cloud-helm/pull/49
Fixes #203, #212 and #161.

2024-02-28 10:09 UTC, jfaltermeier commented
I noticed that there are some left over theia.cloud/v1beta8 AppDefinition references in:
`demo/dockerfiles/demo-operator-custom-template/templateDeployment.yaml`
`demo/dockerfiles/demo-operator-custom-template/templateDeploymentWithoutOAuthProxy.yaml`
`helm/theia.cloud/test/cdt.yaml`
`terraform/test-configurations/2-01_try-now/theia_cloud.tf`
`terraform/test-configurations/2-03_try-now_paths/theia_cloud.tf`

2024-02-28 11:16 UTC, jfaltermeier reviewed
Thanks, I had a first look at the code and it looks very good already. 
I will start some testing now as well.

2024-02-28 11:16 UTC, jfaltermeier commented on java/conversion/org.eclipse.theia.cloud.conversion/src/main/java/org/eclipse/theia/cloud/conversion/ConversionEndpoint.java
> +	    System.out.println("[" + conversionReview.getRequest().getUid() + "] Converting "
I think we should use the `org.jboss.logging.Logger` from quarkus (like in the service) rather than sysouts. 
Also we might include the path in the message, just to see if an app definition ends up at the workspace endpoint, because of an error

2024-02-28 13:00 UTC, sgraband commented
> Could you please check if you get changes on the settings in different IDEs? If yes we should check if we can fix this (probably in a follow up ticket), because the settings should not get added to .gitignore, if possible.

Looks good on my side. Tested also with VSCode, TheiaIDE and Eclipse

2024-02-28 14:11 UTC, sgraband commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/appdefinition/hub/AppDefinitionHub.java
> +	this.timeoutStrategy = Optional.of("FIXEDTIME");
I do not have a string opinion here as well. I would just say we should keep this as flexible as possible, as we do not know what migrations might happen in the future.
But setting default values for deprecated fields makes sense for me. Older versions toHub functions should have been written earlier anyway, hence they should still set the correct value if it was there in the old version.

Are you fine with that approach? Or do you have additional ideas on how to improve this further?

2024-03-01 11:55 UTC, jfaltermeier requested changes
I've found two more mixups in the Hub. 
After those are fixed, I think we can approve and merge this. 
This was the only issue I found during the second test. 

Also I pushed one commit updating the AppDefinitions in the tf files I used for testing

2024-03-01 11:55 UTC, jfaltermeier commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/appdefinition/hub/AppDefinitionHub.java
> +			.of(toHub.getSpec().getMonitor().getActivityTracker().getNotifyAfter());
`getTimeoutAfter`

2024-03-01 11:55 UTC, jfaltermeier commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/appdefinition/hub/AppDefinitionHub.java
> +			.of(toHub.getSpec().getMonitor().getActivityTracker().getNotifyAfter());
`getTimeoutAfter`

2024-03-01 11:55 UTC, jfaltermeier commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/appdefinition/hub/AppDefinitionHub.java
> +	this.timeoutStrategy = Optional.of("FIXEDTIME");
Sounds good, let's add default values for deprecated fields

2024-03-04 11:14 UTC, jfaltermeier approved these changes
Thanks, LGTM!

2024-03-04 13:57 UTC, merged