Setup node mono repo and implement Try Now page
eclipsesource/theia-cloud pull request #39
Opened 2022-05-18 16:30 UTC by lucas-koehler

* Setup mono repo with npm workspaces including tsconfig, prettier, eslint
* Setup common typescript, prettier and ESLint settings
* Implement Try Now page
* Improve minikube readme
* Add Dockerfile for the Try Now page
* Add .dockerignore file to exclude unneeded files from docker build contexts

Fixes #29

![image](https://user-images.githubusercontent.com/6959840/169094566-76ba82e9-df40-434d-8790-06cc137f4715.png)

2022-05-19 09:11 UTC, jfaltermeier requested changes
Looks very good and works as expected. I only have some minor comments and some questions.

2022-05-19 10:41 UTC, lucas-koehler commented on node/common/src/workspace.ts
> +  const { appId, workspaceServiceUrl, workspaceTemplate, user = uuidv4() + '@theia.cloud' } = options;
Yes, that is exactly what that means :) See here for more information on this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring

2022-05-19 10:43 UTC, lucas-koehler commented on node/common/src/config.ts
> +      !!thing &&
I'd not do it in there because it just fails then without clients ability to know why. Also it doesn't match the interface then. Instead, I'll split the cloud config type and provide a separate check to see if a config is a keycloak config.

2022-05-19 11:07 UTC, lucas-koehler commented
@jfaltermeier Thanks for the review. I pushed another commit to address the comments. For the config typeguard, I added another explicit typeguard to check whether something configures keycloak.
Clients need to check the theia configs `useKeycloak` flag explicitly anyway to decide on how to proceed. Now they can then check whether the config is also a keycloak config to access the properties in a typesafe way without needing to force away the `| undefined` with a `!`.

2022-05-19 11:10 UTC, lucas-koehler commented
@jfaltermeier The force push of the feedback commit was because I missed something in the new typeguard. Now it should be correct :)

2022-05-20 09:26 UTC, jfaltermeier approved these changes
LGTM, thanks!

2022-05-20 09:26 UTC, merged