Introduce workspace resource, inactivity strategy, and extend REST API
eclipsesource/theia-cloud pull request #62
Opened 2022-07-26 09:46 UTC by martin-fleck-at

App Definition:
- Replace 'killAfter' with 'timeoutStrategy' and 'timeoutLimit'
-- Timeout can be specified on the app definition
-- Timeout can be specified as value/args to override app definition
-- Strategies are contributed via dependency injection

Session:
- Add 'lastActivity' to session to reflect last user interaction
-- Support 'INACTIVITY' strategy for timeout
-- Add REST API to report activity for a given session

Workspace:
- Introduce new workspace resource
-- Represents cross-section of app definition, user and storage
-- Active workspaces have sessions with new 'workspaceName' field
-- Storage contains workspace name as label
- A workspace is associated with a persisted storage (create, delete)

REST API:
- Session resource: List, start, stop, report activity
- Workspace resource: List, create, delete
- Root resource (previous): Launch (create workspace + start session)

Configuration and Templates:
- Add values 'servicePort', 'serviceProtocol' for detailed URL spec
- Add configuration for sessions per user
- Add default environment variables to deployment to use REST API

Refactorings:
- Use DI bindings to improve customizability and ease implementations
- Replace KillAfterRunnable with overridable method

Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>

2022-08-01 13:17 UTC, jfaltermeier requested changes
Hi, thank you for the PR! I've had a first look and have a few comments. 
Main topics are 
* whether the Workspace needs to know its AppDefinition (In my opinion no. If someone want to limit this, this should be part of their application logic. We might allow adding tags or something like this to workspaces then)
* state (correlationId) in the kubernetes resource clients which does not work with multiple threads and singletons
* some smaller comments
I have not tested the changes yet, because there are some blocking issues with the helm chart e.g.

2022-08-01 13:17 UTC, jfaltermeier commented on node/common/src/session.ts
> +export async function createAndLaunchSession(options: SessionLaunchRequest, retries = 0): Promise<void> {
This does not use workspaces yet?

2022-08-02 11:06 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/SessionSpec.java
> +    public void setWorkspace(String workspace) {
I removed all unnecessary setters.

2022-08-02 11:06 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/SessionSpec.java
> +		+ ", error=" + error + ", lastActivity=" + lastActivity + "]";
Done.

2022-08-02 11:06 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/Workspace.java
> +    private static final long serialVersionUID = 4518092300237069237L;
Fixed.

2022-08-02 11:06 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/WorkspaceSpec.java
> +	return "WorkspaceSpec [name=" + name + ", label=" + label + ", appDefinition=" + appDefinition + ", user="
Done.

2022-08-02 11:07 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/WorkspaceSpec.java
> +    public String getAppDefinition() {
I thought a persisted volume only pertains to a single app definition but you are right that some volumes may also be re-used by other app definitions. I kept the value to specify the last app definition that was used on this workspace. So if someone wants to start a workspace again, they do not need to know which was the app definition that was used to create the workspace. However, they still have the options to override it.

2022-08-02 11:07 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/resource/WorkspaceSpec.java
> +    public WorkspaceSpec(String error) {
Removed it.

2022-08-02 11:07 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/K8sUtil.java
> +    private static TheiaCloudClient CUSTOM_CLIENT = new DefaultTheiaCloudClient(CLIENT).inNamespace("theiacloud");
We now do not set any namespaces explicitly and assume that the kubernetes client detects the correct namespace by default.

2022-08-02 11:08 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/client/BaseResourceClient.java
> +	this.correlationId = correlationId;
You are right, this state may cause problems. I removed the state and added the correlationId to all edit-methods so that we do not run into any threading/re-use problems.

2022-08-02 11:08 UTC, martin-fleck-at commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/k8s/client/ResourceClient.java
> +    default ResourceClient<T, L> interaction() {
You are right, I removed the field.

2022-08-02 11:09 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/RootResource.java
> +	WorkspaceCreationResponse response = new WorkspaceResource().createWorkspace(request);
Understood, I changed it so we do not create any "injectable" objects through constructors.

2022-08-02 11:09 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/RootResource.java
> +	SessionLaunchResponse launchResponse = new SessionResource()
Done.

2022-08-02 11:09 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/ServiceResponse.java
> +public class ServiceResponse {
Done.

2022-08-02 11:09 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/workspace/UserWorkspace.java
> +    public String appDefinition;
See my comment above, I'd like to keep it unless you insist otherwise.

2022-08-02 11:11 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/workspace/WorkspaceCreationRequest.java
> +	this.appDefinition = appDefinition;
You are right, this is not strictly needed. However, I think it still makes sense to prepare a workspace for a specific app definition. If you disagree I can remove the argument or make it at least optional.

2022-08-02 11:11 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/ServiceRequest.java
> +public class ServiceRequest {
Done.

2022-08-02 11:11 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/session/SessionResource.java
> +	if (request.workspaceName == null) {
I split the use case now into starting a session with an existing workspace and an ephemeral session.

2022-08-02 11:12 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/session/SessionResource.java
> +	    LOGGER.info(formatLogMessage(correlationId, "No workspace for given name: " + request.workspaceName));
This is only true for the "create and launch" method at the root level. The SessionResource itself either assumes a workspace is already present or we do not need one.

2022-08-02 11:12 UTC, martin-fleck-at commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/di/AbstractTheiaCloudOperatorModule.java
> +	return new DefaultAppDefinitionResourceClient(client);
I removed the state so we can keep the singletons as far as I can tell.

2022-08-02 11:12 UTC, martin-fleck-at commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/LazyWorkspaceHandler.java
> +	if (arguments.isEphemeralStorage()) {
Yeah, I actually really like that. I removed the argument. Great idea!

2022-08-02 11:13 UTC, martin-fleck-at commented on helm/theia.cloud/crds/workspace-spec-resource.yaml
> +                appDefinition:
We keep it only to track the last used app definition.

2022-08-02 11:13 UTC, martin-fleck-at commented on helm/theia.cloud/templates/landing-page-config-map.yaml
> +      serviceUrl: "{{ .Values.hosts.serviceProtocol }}://{{ .Values.hosts.service }}:{{ .Values.hosts.servicePort }}/service",
I see, I guarded the expression accordingly.

2022-08-02 11:13 UTC, martin-fleck-at commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/TheiaCloudArguments.java
> +    private String timeoutStrategy;
Perfect, I agree. One less option to hand in ;-)

2022-08-02 11:14 UTC, martin-fleck-at commented on helm/theia.cloud/values.yaml
> +  timeoutStrategy: "FIXEDTIME"
Done.

2022-08-02 11:14 UTC, martin-fleck-at commented on helm/theia.cloud/values.yaml
> +  # port of the REST-API
Done.

2022-08-02 11:14 UTC, martin-fleck-at commented on node/common/src/session.ts
> +export async function createAndLaunchSession(options: SessionLaunchRequest, retries = 0): Promise<void> {
We have the same split as on the server: "pure" workspace handling, "pure" session handling and the root-level launch which combines workspace creation with session launch.

2022-08-02 11:17 UTC, martin-fleck-at commented
@jfaltermeier Thank you for your review so far, I tried to address all your comments in an additional commit. Please let me know what you think.

2022-08-03 10:39 UTC, jfaltermeier requested changes
Thank you very much @martin-fleck-at 
The changes look good as far as I could see. I will now start some manual testing. 

I have two small comments about documentation/helm chart
Also I've merged a small change to main, so there are two conflicts :see_no_evil:

2022-08-03 10:39 UTC, jfaltermeier commented on helm/theia.cloud/templates/landing-page-config-map.yaml
> +      serviceUrl: "{{ .Values.hosts.serviceProtocol }}://{{ .Values.hosts.service }}{{ if .Values.operator.servicePort }}:{{ .Values.hosts.servicePort }}{{ end }}/service",
As far as I can see this is not used in any values.yaml yet. 
I think we should at least add it in the main `values.yaml` as an example. 
Also I am not sure about the name `.Values.operator.servicePort `. Here it is used in the landing page, so operator is strange. Could we maybe use `.Values.hosts.useServicePortInHostname `?

2022-08-03 10:39 UTC, jfaltermeier commented on helm/theia.cloud/templates/operator.yaml
> +          - {{ .Values.hosts.serviceProtocol }}://{{ .Values.hosts.service }}{{ if .Values.operator.servicePort }}:{{ .Values.hosts.servicePort }}{{ end }}/service,
See other comment about `.Values.operator.servicePort`

2022-08-03 10:39 UTC, jfaltermeier commented on doc/docs/Architecture.md
>  |--ephemeralStorage|boolean|Whether sessions get persisted storage assigned|
We should remove this as well

2022-08-03 10:41 UTC, jfaltermeier commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/K8sUtil.java
> +    private static TheiaCloudClient CUSTOM_CLIENT = new DefaultTheiaCloudClient(CLIENT).inNamespace("theiacloud");
Fine for me. I will try to test whether this causes issues, but it should be fine

2022-08-03 10:42 UTC, jfaltermeier commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/workspace/UserWorkspace.java
> +    public String appDefinition;
Fine for me

2022-08-03 10:43 UTC, jfaltermeier commented on helm/theia.cloud/crds/workspace-spec-resource.yaml
> +                appDefinition:
Makes sense, thanks!

2022-08-03 12:33 UTC, jfaltermeier commented on helm/theia.cloud/values.yaml
> +  ephemeralStorage: true
This needs to be adjusted on the other value files as well

2022-08-03 12:39 UTC, jfaltermeier commented on helm/theia.cloud/templates/service-role.yaml
> +      - workspaces
This needs to be added in the operator-role.yaml as well. Otherwise we run into 
```
12:37:23.201 [main] ERROR org.eclipse.theia.cloud.operator.TheiaCloudImpl - [init] Error while initializing workspace watch
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/theia.cloud/v1beta/namespaces/theiacloud/workspaces. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. workspaces.theia.cloud is forbidden: User "system:serviceaccount:theiacloud:operator-api-service-account" cannot list resource "workspaces" in API group "theia.cloud" in the namespace "theiacloud".

```

2022-08-03 13:10 UTC, jfaltermeier commented on helm/theia.cloud/templates/service-role.yaml
> +      - workspaces
In the service we get
```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/apiextensions.k8s.io/v1/customresourcedefinitions. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:theiacloud:service-api-service-account" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:683)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:662)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:611)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:556)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:519)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:503)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:131)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:413)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:402)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:83)
	at org.eclipse.theia.cloud.common.util.CustomResourceUtil.registerCustomResource(CustomResourceUtil.java:80)

```

So we probably need the `list` verb and the `customresourcedefinitions` resource

2022-08-03 13:39 UTC, jfaltermeier commented
First Test case is the ephermal Try-Now use case with FixedTime strategy. 

The `config.js` of the landing page looks fine as far as I can see:
```
window.theiaCloudConfig = {
  appId: "asdfghjkl",
  appName: "Theia Blueprint",
  useEphemeralStorage: true,
  useKeycloak: false,
  keycloakAuthUrl: "https://keycloak.192.168.39.2.nip.io/auth/",
  keycloakRealm: "TheiaCloud",
  keycloakClientId: "theia-cloud",
  serviceUrl: "https://service.192.168.39.2.nip.io/service",
  appDefinition: "theia-cloud-demo",
};
```
Despite this config I can see that `Workspace` Resources are created by the Service, which should not be the case in the ephermal use case:

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-08-03 13:25:31,455 INFO  [io.quarkus] (main) service 0.7.0-SNAPSHOT on JVM (powered by Quarkus 2.7.0.Final) started in 1.356s. Listening on: http://0.0.0.0:8081
2022-08-03 13:25:31,462 INFO  [io.quarkus] (main) Profile prod activated. 
2022-08-03 13:25:31,462 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
2022-08-03 13:26:46,524 INFO  [org.ecl.the.clo.ser.BaseResource] (executor-thread-0) [22f156fd-d850-4e60-97c9-c75eda6f38ad] Create workspaceorg.eclipse.theia.cloud.service.LaunchRequest@6b07313a
2022-08-03 13:26:47,181 WARN  [io.fab.kub.cli.int.VersionUsageUtils] (executor-thread-0) The client is using resource type 'workspaces' with unstable version 'v1beta'
2022-08-03 13:27:46,447 INFO  [org.ecl.the.clo.ser.BaseResource] (executor-thread-1) [d17ac656-2c45-4cda-9e4e-d243b25b7d44] Create workspaceorg.eclipse.theia.cloud.service.LaunchRequest@683761e5

```

Moreover the Operator fails to create the PV(C)s for the Workspace:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/theiacloud/persistentvolumeclaims. Message: PersistentVolumeClaim "ws-theia-cloud-demo-8940c3d5-f1ba-4bc7-a906-dbf27351f178attheia-cloud-1659533206527-pvc" is invalid: metadata.labels: Invalid value: "ws-theia-cloud-demo-8940c3d5-f1ba-4bc7-a906-dbf27351f178attheia-cloud-1659533206527": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "ws-theia-cloud-demo-8940c3d5-f1ba-4bc7-a906-dbf27351f178attheia-cloud-1659533206527": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=PersistentVolumeClaim, name=ws-theia-cloud-demo-8940c3d5-f1ba-4bc7-a906-dbf27351f178attheia-cloud-1659533206527-pvc, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=PersistentVolumeClaim "ws-theia-cloud-demo-8940c3d5-f1ba-4bc7-a906-dbf27351f178attheia-cloud-1659533206527-pvc" is invalid: metadata.labels: Invalid value: "ws-theia-cloud-demo-8940c3d5-f1ba-4bc7-a906-dbf27351f178attheia-cloud-1659533206527": must be no more than 63 characters, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:683) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:662) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:613) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:556) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:519) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:306) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:642) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:83) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:61) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.common.k8s.client.BaseResourceClient.loadAndCreate(BaseResourceClient.java:98) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.common.k8s.client.ResourceClient.loadAndCreate(ResourceClient.java:68) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.operator.handler.impl.DefaultPersistentVolumeCreator.createAndApplyPersistentVolumeClaim(DefaultPersistentVolumeCreator.java:73) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.operator.handler.impl.LazyWorkspaceHandler.workspaceAdded(LazyWorkspaceHandler.java:41) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.operator.TheiaCloudImpl.handleWorkspaceEvent(TheiaCloudImpl.java:185) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.operator.TheiaCloudImpl.initWorkspace(TheiaCloudImpl.java:130) ~[operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
at org.eclipse.theia.cloud.operator.TheiaCloudImpl.initWorkspacesAndWatchForChanges(TheiaCloudImpl.java:100) [operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.operator.TheiaCloudImpl.start(TheiaCloudImpl.java:81) [operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.operator.Main.runMain(Main.java:50) [operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
at org.eclipse.theia.cloud.operator.Main.main(Main.java:38) [operator-0.7.0-SNAPSHOT-jar-with-dependencies.jar:?]
```

2022-08-03 13:43 UTC, jfaltermeier commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/RootResource.java
> +	info(correlationId, "Create workspace" + request);
Missing space

2022-08-03 13:44 UTC, jfaltermeier commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/ServiceRequest.java
> +public class ServiceRequest {
Please check whether all subclasses have proper toString() methods since the requests are getting logged

2022-08-04 15:09 UTC, martin-fleck-at commented on helm/theia.cloud/templates/operator.yaml
> +          - "--timeoutStrategy"
Done.

2022-08-04 15:16 UTC, martin-fleck-at commented on helm/theia.cloud/templates/landing-page-config-map.yaml
> +      serviceUrl: "{{ .Values.hosts.serviceProtocol }}://{{ .Values.hosts.service }}{{ if .Values.operator.servicePort }}:{{ .Values.hosts.servicePort }}{{ end }}/service",
If I understand you correctly we should adapt the port to a boolean flag which indicates whether we should use the known service port 8081 in the hostname, right? I made the changes accordingly.

2022-08-04 15:16 UTC, martin-fleck-at commented on helm/theia.cloud/templates/operator.yaml
> +          - {{ .Values.hosts.serviceProtocol }}://{{ .Values.hosts.service }}{{ if .Values.operator.servicePort }}:{{ .Values.hosts.servicePort }}{{ end }}/service,
Done.

2022-08-04 15:17 UTC, martin-fleck-at commented on doc/docs/Architecture.md
>  |--ephemeralStorage|boolean|Whether sessions get persisted storage assigned|
Done.

2022-08-04 15:17 UTC, martin-fleck-at commented on helm/theia.cloud/values.yaml
> +  ephemeralStorage: true
Done.

2022-08-04 15:17 UTC, martin-fleck-at commented on helm/theia.cloud/templates/service-role.yaml
> +      - workspaces
I made the changes that you requested. Now I only do the CR verification on the operator but not the service.

2022-08-04 15:17 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/RootResource.java
> +	info(correlationId, "Create workspace" + request);
Done.

2022-08-04 15:18 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/ServiceRequest.java
> +public class ServiceRequest {
All subclasses should have a proper toString() now, sorry for missing some!

2022-08-04 15:20 UTC, martin-fleck-at commented
@jfaltermeier Thank you very much for your feedback! Unfortunately, I cannot reproduce the issue with the ephemeral workspace creating a workspace. I am using postman to send a request that looks like this:
`POST http://localhost:8081/service { "appDefinition": "theia-cloud-demo", "user": "foo@theia-cloud.io", "ephemeral": "true", "appId": "asdfghjkl" }`

Can you check whether you also run into this problem when making this call directly? Probably there is still something missing but I need to be able to reproduce this first.

2022-08-08 11:39 UTC, jfaltermeier commented
Test Values:
```
app:
  id: asdfghjkl
  name: Theia Blueprint
  logo: theiablueprint.png

issuer:
  email: mmorlock@example.com

image:
  name: theiacloud/theia-cloud-demo:test
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "3"

hosts:
  service: service.192.168.39.3.nip.io
  serviceProtocol: https
  landing: theia.cloud.192.168.39.3.nip.io
  instance: ws.192.168.39.3.nip.io

landingPage:
  image: theiacloud/theia-cloud-landing-page:test
  # imagePullSecret: pullsecret
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: false

keycloak:
  enable: true
  authUrl: "https://keycloak.192.168.39.3.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  image: theiacloud/theia-cloud-operator:test
  # imagePullSecret: pullsecret
  eagerStart: false
  cloudProvider: "K8S"
  bandwidthLimiter: "K8SANNOTATION"

service:
  image: theiacloud/theia-cloud-service:test
  # imagePullSecret: pullsecret

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: theia-cloud-selfsigned-issuer
  theiaCloudCommonName: true
```

I can see that the Workspace CR is created and the Operator creates a persistent volume and persistent volume claim accordingly. However this does not get mounted in the running instance. The pod spec looks like this:

```
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - --config=/etc/oauth2-proxy.cfg
    - --authenticated-emails-file=/emails/authenticated-emails-list
    - --gcp-healthchecks
    - --reverse-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy
    imagePullPolicy: Always
    name: oauth2-proxy
    ports:
    - containerPort: 5000
      name: web
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/oauth2-proxy.cfg
      name: oauth2-proxy-config
      subPath: oauth2-proxy.cfg
    - mountPath: /templates
      name: oauth2-templates
    - mountPath: /emails
      name: oauth2-emails
  - env:
    - name: THEIA_CLOUD_APP_ID
      value: asdfghjkl
    - name: THEIA_CLOUD_SERVICE_URL
      value: https://service.192.168.39.2.nip.io/service,
    - name: THEIA_CLOUD_SESSION_UID
      value: 5f89c85d-fc05-4f17-8f8a-80baed316706
    - name: THEIA_CLOUD_SESSION_NAME
      value: ws-asdfghjkl-theia-cloud-demo-foo-theia-cloud-io-session
    - name: THEIA_CLOUD_SESSION_USER
      value: foo@theia-cloud.io
    - name: THEIA_CLOUD_SESSION_URL
      value: https://service.192.168.39.2.nip.io/service,
    image: theiacloud/theia-cloud-demo:test
    imagePullPolicy: IfNotPresent
    name: theia-cloud-demo
    ports:
    - containerPort: 3000
      protocol: TCP
    resources:
      limits:
        cpu: "2"
        memory: 1200M
      requests:
        cpu: 100m
        memory: 1G
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsUser: 101
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: ws-asdfghjkl-theia-cloud-demo-foo-theia-cloud-io-session-confi
    name: oauth2-proxy-config
  - configMap:
      defaultMode: 420
      name: oauth2-templates
    name: oauth2-templates
  - configMap:
      defaultMode: 420
      name: ws-asdfghjkl-theia-cloud-demo-foo-theia-cloud-io-session-email
    name: oauth2-emails

```

2022-08-08 11:49 UTC, jfaltermeier commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/LazyWorkspaceHandler.java
> +	resourceClient.persistentVolumeClaims().delete(correlationId, storageName);
Have you checked whether it would be possible to set a owner reference (https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications) on the persistent volume and claim which points to the workspace?
Usually if the owner is deleted, the dependent objects are deleted by kubernetes automatically. 
We use this for the workspace deployments for example. 

So it might be possible to delegate this kubernetes.

2022-08-08 12:07 UTC, jfaltermeier commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/LazyWorkspaceHandler.java
> +	resourceClient.persistentVolumeClaims().delete(correlationId, storageName);
Also I think we need more logging here. Currently we have no logs although something gets deleted.

2022-08-09 11:52 UTC, martin-fleck-at commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/LazyWorkspaceHandler.java
> +	resourceClient.persistentVolumeClaims().delete(correlationId, storageName);
Very nice, you are correct. When I add the workspace owner reference the storage gets deleted automatically. Thank you for the tip!

2022-08-09 11:52 UTC, martin-fleck-at commented on helm/theia.cloud/valuesCDT.yaml
> +  servicePort: 8081
Sorry for that, I fixed it.

2022-08-09 11:53 UTC, martin-fleck-at commented
@jfaltermeier Thank you again for the review. You were right, we were not deriving the storage name correctly which is why it never got properly mounted. I fixed that now as well.

2022-08-09 13:03 UTC, jfaltermeier commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/LazyWorkspaceHandler.java
> +	resourceClient.persistentVolumeClaims().delete(correlationId, storageName);
As far as I can see the Persistent Volume Claim gets deleted but the Persistent Volume is not :-(
So I fear we have to delete the volume manually

2022-08-09 14:35 UTC, martin-fleck-at commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/LazyWorkspaceHandler.java
> +	resourceClient.persistentVolumeClaims().delete(correlationId, storageName);
I restored the deletion behavior to how it was. If it is already gone the deletion does not cause any harm but if somebody overwrites the PersistentVolumeCreator it's still good to have the deletion in the handler that actually triggers the creation I believe.

2022-08-10 08:34 UTC, jfaltermeier commented
I think this will be the last comment now. Volume deletion works and all new Rest API as well but reporting activity. The rest service logs this:
```
2022-08-10 08:30:36,669 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /service/session failed, error id: 56c0ea05-5b05-4b95-8b46-68b1b257d875-1: org.jboss.resteasy.spi.UnhandledException: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://10.96.0.1/apis/theia.cloud/v1beta/namespaces/theiacloud/sessions/ws-1660120126741theia-cloud-demo-foo-theia-cloud-io-session. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. sessions.theia.cloud "ws-1660120126741theia-cloud-demo-foo-theia-cloud-io-session" is forbidden: User "system:serviceaccount:theiacloud:service-api-service-account" cannot patch resource "sessions" in API group "theia.cloud" in the namespace "theiacloud".
```

2022-08-10 11:32 UTC, jfaltermeier approved these changes
Thank you for the contribution. I will publish this as 0.8.0.MS3

2022-08-10 11:33 UTC, merged

2022-08-10 12:48 UTC, jfaltermeier commented
Fixes #52