Add OpenAPI specs for Theia.cloud service
eclipsesource/theia-cloud pull request #66
Opened 2022-08-12 10:10 UTC by jfaltermeier

* enable OpenAPI generation
* add annotations
* commit resulting json under doc/docs/openapi.json

Easy way to test would be launching a swagger-ui via docker:
```
docker pull swaggerapi/swagger-ui
docker run -p 80:8080 swaggerapi/swagger-ui
```
then browsing to http://localhost/ and exploring the spec from here: https://raw.githubusercontent.com/jfaltermeier/theia-cloud/jf/restapi/doc/docs/openapi.json

2022-08-15 10:19 UTC, martin-fleck-at requested changes
Hi @jfaltermeier, Thank you very much for that change, I think that will help people to explore the REST API a lot! I only have one minor comment regarding an optional field.

2022-08-15 10:19 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/workspace/WorkspaceCreationRequest.java
> +    @Schema(title = "The label of the workspace", required = true)
I think the label is actually optional as it can be generated based on the user and the app definition. At least the workspace creation still seems to work without it.

2022-08-15 10:19 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/workspace/WorkspaceCreationRequest.java
> +    @Schema(title = "The app this workspace will be used with.", required = false)
The appDefinition is not strictly needed but I saw that the label and name generation still depend on it, so we now get `null` in the name and label of the workspace which is not a problem, just doesn't look very nice. So maybe we should mark it required for now or ensure that we consider null values in the name and label generation, what do you think?

2022-08-16 08:11 UTC, jfaltermeier commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/workspace/WorkspaceCreationRequest.java
> +    @Schema(title = "The app this workspace will be used with.", required = false)
I've changed to label generation in a follow up commit

2022-08-16 08:12 UTC, jfaltermeier commented
Thanks for the review. I've added a further commit addressing the comments.

2022-08-16 08:27 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/workspace/WorkspaceCreationRequest.java
> +    @Schema(title = "The app this workspace will be used with.", required = false)
Perfect, thank you!

2022-08-16 08:28 UTC, martin-fleck-at approved these changes
Great, everything looks good to me now, thank you Johannes!

2022-08-16 08:31 UTC, merged