Improve REST API
eclipsesource/theia-cloud pull request #83
Opened 2022-09-07 07:50 UTC by martin-fleck-at

Ensure list session request only reports user-specific sessions

Switch from custom error responses to REST error codes
- Introduce custom TheiaCloud errors
- Introduce custom TheiaCloud exception that is mapped to errors
- Remove custom error responses and regenerate REST client

Fix problem with Theia activity tracker
- Switch back to axios-based client API to avoid dependency issues
-- 'fetch' may not be available on node backend of Theia

2022-09-07 08:25 UTC, jfaltermeier reviewed
Thank you. I have some small comments after the code review. 
I will start testing now.

2022-09-07 08:25 UTC, jfaltermeier commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/BaseResource.java
> +	    String methodName = Thread.currentThread().getStackTrace()[2].getMethodName();
Isn't the `[2]` too brittle? I think this fails if e.g. two method would delegate to a shared util method, which then evaluates the request.

2022-09-07 08:25 UTC, jfaltermeier commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/TheiaCloudWebException.java
> +	if (error != null) {
I think we should also check if the error is blank to be consistent with `SessionSpec.hasError()` and `WorkspaceSpec.hasError()`. 
Maybe we should actually use those `hasError()` methods above?

2022-09-07 08:25 UTC, jfaltermeier commented on node/common/src/client.ts
> +  export async function launch(request: LaunchRequest, retries = 0, timeout?: number, redirect = true): Promise<void> {
Should we return the URL here? If redirect is false we might want to receive the URL

2022-09-07 09:09 UTC, Hadsch commented on node/common/src/client.ts
> +  export async function launch(request: LaunchRequest, retries = 0, timeout?: number, redirect = true): Promise<void> {
Yes this would be good ;)

2022-09-07 09:41 UTC, jfaltermeier commented
I've verified launching with both our landing pages and checked the activity reporting, which works fine again with the generated code using axios. 
For the rest API I've tested listSessions, which now returns the sessions of the user provided in the path

2022-09-07 10:52 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/BaseResource.java
> +	    String methodName = Thread.currentThread().getStackTrace()[2].getMethodName();
Good point! I removed the methodName and log the request kind instead, together with a trace of the actual request.

2022-09-07 10:52 UTC, martin-fleck-at commented on java/service/org.eclipse.theia.cloud.service/src/main/java/org/eclipse/theia/cloud/service/TheiaCloudWebException.java
> +	if (error != null) {
Good catch! I unified the handling for these methods.

2022-09-07 10:53 UTC, martin-fleck-at commented on node/common/src/client.ts
> +  export async function launch(request: LaunchRequest, retries = 0, timeout?: number, redirect = true): Promise<void> {
I totally agree, I created a separate method `launchAndRedirect` that includes the redirection in a successful launch case. I also added the retry mechanism to all our REST client methods for further convenience.

2022-09-07 12:08 UTC, martin-fleck-at commented
@jfaltermeier Thank you for the fast review, I pushed an update which should address all concerns.

2022-09-08 08:26 UTC, jfaltermeier requested changes

2022-09-08 08:26 UTC, jfaltermeier commented on node/common/src/client.ts
> +    const url = await launch(request, retries, timeout);
Timeout and retry are switched up here

2022-09-08 12:42 UTC, jfaltermeier commented on node/landing-page/src/components/SessionLauncher.vue
> +      TheiaCloud.launchAndRedirect(this.useEphemeralStorage
We are not passing the user email anymore which results in an anonymous user all the time.

2022-09-08 15:39 UTC, martin-fleck-at commented on node/landing-page/src/components/SessionLauncher.vue
> +      TheiaCloud.launchAndRedirect(this.useEphemeralStorage
You are right, I pushed another fix, thank you for your thorough review!

2022-09-12 07:36 UTC, jfaltermeier approved these changes
Thanks, lgtm!

2022-09-12 07:36 UTC, merged