Allow to launch multiple apps via try now page
eclipsesource/theia-cloud pull request #94
Opened 2022-10-17 12:55 UTC by jfaltermeier

**For testing the try now page itself without Theia.cloud service+operator**

Open `node/try-now-page/public/config.js` and uncomment the `additionalApps`
Build and launch the webpage with `npm run build && npm run start -w try-now-page`

`http://localhost:3000` should have the default Theia Blueprint selected. 

`http://localhost:3000/?appDef=coffee-editor` should have coffee-editor preselected. 

When attempting to launch an app, you have to check the console out to verify the app, which is attempted to be launched:
```
Launching theia-cloud-demo
Launching coffee-editor
Launching cdt-cloud-demo
```

**For testing via minikube**

Build the docker images (https://github.com/eclipsesource/theia-cloud/blob/main/doc/docs/platforms/Minikube.md#testing-local-images) and adjust the images in `helm/theia.cloud/valuesMinikube.yaml` accordingly (remember to also switch from `theiacloud/theia-cloud-landing-page` to `theiacloud/theia-cloud-try-now-page`)
Besides that also disable keycloak:
```
keycloak:
  enable: false
```
and uncomment the `additionalApps` and set `ephemeralStorage` to `true`:
```
  ephemeralStorage: true
  additionalApps: 
    coffee-editor:
      label: "Coffee Editor"
    cdt-cloud-demo:
      label: "CDT.cloud Blueprint"
```
Install Theia.cloud via helm with the `valuesMinikube.yaml`

Then adjust the host in `demo/k8s/appdefinitions/cdt.yaml` and `demo/k8s/appdefinitions/coffee-editor.yaml` to match your minikube instances host. 
Install both yamls with `kubectl apply -f cdt.yaml && kubectl apply -f coffee-editor.yaml`

2022-10-31 10:53 UTC, AlexandraBuzila requested changes
Looking good! There's one corner case that should still be handled, to avoid breaking the page when the `appDef` value provided via url is invalid.

2022-10-31 10:53 UTC, AlexandraBuzila commented on node/try-now-page/src/App.tsx
> +          setSelectedAppName((element as HTMLSelectElement).options[(element as HTMLSelectElement).selectedIndex].text);
If the `defaultSelection` is a value not present in `config.additionalApps`, the `selectedIndex` will be -1 and this line will throw an error. 
In that case, the default app definition should probably be used.

2022-11-03 10:33 UTC, jfaltermeier commented on node/try-now-page/src/App.tsx
> +          setSelectedAppName((element as HTMLSelectElement).options[(element as HTMLSelectElement).selectedIndex].text);
Thanks. I've pushed an additional commit that will check whether the default selection is valid.

2022-11-07 10:11 UTC, jfaltermeier commented
@AlexandraBuzila When would you have time for a short re-review?
We will do a milestone release when this one is merged.

2022-11-07 10:48 UTC, AlexandraBuzila approved these changes
Thanks, LGTM!

2022-11-07 13:21 UTC, merged